config/routes.rb
Billing::Application.routes.draw do
  resources :orders

  get "orders/new/express"

  resources :homes
  resources :order_transactions

  root :to => "orders#index"
end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :express_payer_id, :express_token, :card_number, :card_verification, :card_expires, :card_type, :cart_id, :first_name, :ip_address, :last_name, :new
  has_many :transactions, :class_name => "OrderTransaction"
  attr_accessor :card_number, :card_verification

  validate :validate_card, :on => :create

  def purchase
  	response = process_purchase
  end

  def price_in_cents
  	(100*100).round
  end

  def express_token=(token)
    self[:express_token] = token
    if new_record? && !token.blank?
      details = EXPRESS_GATEWAY.details_for(token)
      self.express_payer_id = details.payer_id
      self.first_name = details.params["first_name"]
      self.last_name = details.params["last_name"]
    end
  end

  private

  def process_purchase
    if express_token.blank?
      STANDARD_GATEWAY.purchase(price_in_cents, credit_card, standard_purchase_options)
    else
       EXPRESS_GATEWAY.purchase(price_in_cents, express_purchase_options)
    end
    
  end

  def standard_purchase_options
  	{
  		:ip => ip_address,
  		:billing_address => {
  			:name => "Ryan Bates",
  			:address1 => "123 Main St.",
  			:city => "New York",
  			:state => "NY",
  			:country => "US",
  			:zip => "10001"
  		}
  	}
  end

  def express_purchase_options
    {
      :ip => ip_address,
      :token => express_token,
      :payer_id => express_payer_id
    }
  end

  def validate_card
  	if express_token.blank? && !credit_card.valid?
  		credit_card.errors.full_messages.each do |message|
  			errors.add(:base, message)
  		end
  	end
  end

  def credit_card
  	@credit_card ||= ActiveMerchant::Billing::CreditCard.new(
  		:type => card_type,
  		:number => card_number,
  		:verification_value => card_verification,
  		:month => card_expires.month,
  		:year => card_expires.year,
  		:first_name => first_name,
  		:last_name => last_name
  	)
  end

end

app/models/order_transaction.rb
class OrderTransaction < ActiveRecord::Base
  attr_accessible :action, :amount, :authorization, :message, :order_id, :params, :success
  belongs_to :order
  serialize :params


  def response=(response)
  	self.success		= response.success?
  	self.authorization	= response.authorization
  	self.message		= response.message
  	self.params			= response.params
  rescue ActiveMerchant::ActiveMerchantError => e
  	self.success		= false
  	self.authorization	= nil
  	self.message		= e.message
  	self.params			= {}
  end
end

app/models/purchase.rb
require "rubygems"
require "active_merchant"

ActiveMerchant::Billing::Base.mode = :test

gateway = ActiveMerchant::Billing::PaypalGateway.new(
	:login => "markav_1346897840_biz_api1.gmail.com",
    :password => "1346897888",
    :signature => "A7rjwRXU9YZV2pvUrkKzBmVatsP1AkSAK9dZHdbKP9dEkDQRD1.DcPsP"
)

credit_card = ActiveMerchant::Billing::CreditCard.new(
	:type				=> "visa",
	:number				=> "4024007148673576",
	:verification_value	=> "123",
	:month				=> 1,
	:year				=> Time.now.year+1,
	:first_name			=> "Ryan",
	:last_name			=> "Bates"
)

if credit_card.valid?
	response = gateway.purchase(1000, credit_card, :ip => "127.0.0.1")
	if response.success?
		puts "Purchase Success"
	else
		puts "Nuhhh.. #{response.message}"
	end
else
	puts "Error: credit card is not valid. #{credit_card.errors.full_messages.join('. ')}"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
		
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def express
    response = EXPRESS_GATEWAY.setup_purchase(100,
      :ip                 => request.remote_ip,
      :return_url         => new_order_url,
      :cancel_return_url  => products_url
    )
    redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token)
  end

  def index
    response = EXPRESS_GATEWAY.setup_purchase(100,
     :ip                 => request.remote_ip,
     :return_url         => new_order_url,
     :cancel_return_url  => new_order_url
    )
    redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token)
    @order = Order.all
  end
  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new(:express_token => params[:token])
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /ordersw
  # POST /orders.json
  def create
    @order = Order.new(params[:order])
    @order.ip_address = request.remote_ip
      if @order.save
        if @order.purchase
          render :action => "success"
        else
          puts "*********************"
          puts @order.response
          puts "*********************"
          render :action => "failure"
        end
      else
        render :action => 'new'
      end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/homes/index.html.erb
Home<br/>
<%= link_to "Purchase", new_order_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Billing</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div>
		<font face='arial'>
			<%= yield %>
		</font>
	</div>
</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br />
    <%= f.number_field :cart_id %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :card_type %><br />
    <%= f.select :card_type, [["Visa", "visa"], ["MasterCarad", "master"], ["Discover", "discover"], ["American Express", "american_express"]] %>
  </div>
  <div class="field">
    <%= f.label :card_number %><br />
    <%= f.text_field :card_number %>
  </div>
  <div class="field">
    <%= f.label :card_verification, "Card Verification Code (CVV)" %><br />
    <%= f.text_field :card_verification %>
  </div>
  <div class="field">
    <%= f.label :card_expires %><br />
    <%= f.date_select :card_expires, :discard_day => true, :start_year => Date.today.year, :end_year => (Date.today.year+10), :add_month_numbers => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/failure.html.erb
FAILURE!

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>New</th>
    <th>Cart</th>
    <th>Ip address</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Card type</th>
    <th>Card expires</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.new %></td>
    <td><%= order.cart_id %></td>
    <td><%= order.ip_address %></td>
    <td><%= order.first_name %></td>
    <td><%= order.last_name %></td>
    <td><%= order.card_type %></td>
    <td><%= order.card_expires %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>
<%= link_to image_tag("https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif"), orders_new_express_path %>

app/views/orders/new.html.erb
<%= form_for @order do |f| %>
  

  <% if @order.express_token.blank? %>
  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :card_type %><br />
    <%= f.select :card_type, [["Visa", "visa"], ["MasterCard", "master"], ["Discover", "discover"], ["American Express", "american_express"]] %>
  </p>
  <p>
    <%= f.label :card_number %><br />
    <%= f.text_field :card_number %>
  </p>
  <p>
    <%= f.label :card_verification, "Card Verification Value (CVV)" %><br />
    <%= f.text_field :card_verification %>
  </p>
  <p>
    <%= f.label :card_expires_on %><br />
    <%= f.date_select :card_expires, :discard_day => true, :start_year => Date.today.year, :end_year => (Date.today.year+10), :add_month_numbers => true %>
  </p>
  <% else %>
  <%= f.hidden_field :express_token %>
    <p>Name: <%=h @order.first_name %> <%=h @order.last_name %></p>
    <p>TODO Display order confirmation details</p>
  <% end %>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>New:</b>
  <%= @order.new %>
</p>

<p>
  <b>Cart:</b>
  <%= @order.cart_id %>
</p>

<p>s
  <b>Ip address:</b>
  <%= @order.ip_address %>
</p>

<p>
  <b>First name:</b>
  <%= @order.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @order.last_name %>
</p>

<p>
  <b>Card type:</b>
  <%= @order.card_type %>
</p>

<p>
  <b>Card expires:</b>
  <%= @order.card_expires %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/orders/success.html.erb
SUCCESS!